@startuml

interface Article{
    +getSearchArticleViewName() : String
    +pillSearchArticleContents(type : Integer[], keyword : String[]) : Object
    +getDetailArticleViewName() : String
    +pillDetailArticleContents(id : Integer) : Object
    +wrongMethodParam(e : MethodArgumentTypeMismatchException,httpServletRequest : HttpServletRequest) : ModelAndView
}

class BookController implements Article{

}

class NoticeController implements Article{

}


@enduml